# Generated by Django 5.1.2 on 2024-11-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_recommend',
            field=models.BooleanField(default=True),
        ),
    ]
