# Generated by Django 5.1.2 on 2024-11-06 07:44

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_comment_is_recommended_comment_is_recommend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='comment-text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_recommend',
            field=models.BooleanField(default=True, verbose_name='recommend'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('5', 'Perfect'), ('4', 'good'), ('3', 'normal'), ('2', 'bad'), ('1', 'very bad')], max_length=10, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='comment-author'),
        ),
    ]
